steps:
- name: gcr.io/cloud-builders/bazel@sha256:4a19236baf0e5d663942c3947497e3f5b5356ae3dd6f97b1fae92897a97a11ad
  id: build_server
  args: ['run', '--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64', 'greeter_server:greeter_server_image']

- name: gcr.io/cloud-builders/docker
  id: tag_server
  args: ['tag', 'us-central1-docker.pkg.dev/builder-project/repo1/greeter_server/greeter_server:greeter_server_image', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/greeter_server']
  waitFor: ['build_server']

- name: 'gcr.io/cloud-builders/docker'
  id: push_server
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/greeter_server']
  waitFor: ['tag_server']


- name: gcr.io/cloud-builders/bazel@sha256:4a19236baf0e5d663942c3947497e3f5b5356ae3dd6f97b1fae92897a97a11ad
  id: build_client
  args: ['run', '--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64', 'greeter_client:greeter_client_image']

- name: gcr.io/cloud-builders/docker
  id: tag_client
  args: ['tag', 'us-central1-docker.pkg.dev/builder-project/repo1/greeter_client/greeter_client:greeter_client_image', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/greeter_client']
  waitFor: ['build_client']

- name: 'gcr.io/cloud-builders/docker'
  id: push_client
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/repo1/greeter_client']
  waitFor: ['tag_client']



options:
  machineType: 'N1_HIGHCPU_32'


