steps:
- name: gcr.io/cloud-builders/bazel@sha256:7c34604572d4f001928b98f2b04e2feaebce67b7933e4182b817dcbfe9904bcd
  id: push_server
  args: ['--output_base=/workspace/build_output', 'run',  'greeter_server:push-image']

- name: gcr.io/cloud-builders/bazel@sha256:7c34604572d4f001928b98f2b04e2feaebce67b7933e4182b817dcbfe9904bcd
  id: push_client
  args: ['--output_base=/workspace/build_output', 'run', 'greeter_client:push-image']

options:
  machineType: 'N1_HIGHCPU_32'


